# GET http://localhost:8080/users/1

# GET http://localhost:8080/orders/1

# GET http://localhost:8080/categories/3

# GET http://localhost:8080/products/2

# GET http://localhost:8080/orders/1

# GET http://localhost:8080/products/3


# POST http://localhost:8080/users
# Content-Type: application/json

# { 
#     "name": "Bob Brown", 
#     "email": "bob@gmail.com", 
#     "phone": "977557755", 
#     "password": "123456" 
# } 

# GET http://localhost:8080/users/1

# PUT http://localhost:8080/users/1
# Content-Type: application/json

# {
#     "name": "Maria aaa",
#     "email": "aaaaa@aaa.com",
#     "phone": "aa"
# }



# DELETE http://localhost:8080/users/4