# GET http://localhost:8080/users

# GET http://localhost:8080/users/667caee8424f567eaa3ea8d1/posts
# GET http://localhost:8080/users/

# DELETE http://localhost:8080/users/667c4193e7cae577bdf70692


# POST http://localhost:8080/users
# Content-Type: application/json

# { 
#     "name": "neres", 
#     "email": "neresdev@gmail.com"
# } 

# GET http://localhost:8080/users/667c408e6f61f758e0775783


# PUT http://localhost:8080/users/667c4415ed1641573044ed4b
# Content-Type: application/json

# {
#   "id": "667c4624ce9fa375a79052f7",
#   "name": "Maria Brown updated",
#   "email": "maria@hotmail.com"
# }