version: '3'
services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "12345"
      MYSQL_DATABASE: "coursejdbc"
      MYSQL_USER: "app"
      MYSQL_PASSWORD: "app123"
